<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Animals.aspx.cs" Inherits="Lab_4.Animals1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Список пород</title>
    <style>
        .floatableDiv:after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    
        <div>
            <h1 style="font-family: Impact; background-color: greenyellow; text-align: center;">Просмотр пород животных</h1>
            <span style="display: block; margin: 10px"><a href="/Main.aspx">Назад</a></span>
            <div>
                <div style="text-align: center">
                    <asp:GridView ID="AnimalsTable" runat="server" DataKeyNames="IdA" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True">
                        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                        <AlternatingRowStyle BackColor="White" />
                        <HeaderStyle BackColor="#28a4fb" Font-Bold="True" ForeColor="White" CssClass="Header" />
                        <Columns>
                            <asp:BoundField DataField="IdA" HeaderText="IdA" ReadOnly="True" SortExpression="IdA" Visible="False" />
                            <asp:BoundField DataField="AName" HeaderText="Наименование породы" SortExpression="AName" />
                            <asp:BoundField DataField="Count" HeaderText="Количество" SortExpression="Count" />
                            <asp:BoundField DataField="MarketPrice" HeaderText="Цена за голову" SortExpression="MarketPrice" />
                        </Columns>
                    </asp:GridView>
                </div>
                
                <div class="floatableDiv" style="margin-top: 15px;">
                    <div style="float: left; margin-right: 15px; border: 1px black dashed;">
                        <table>
                        <tr>
                            <td>Наименование породы:</td>
                            <td>
                                <asp:TextBox ID="TextBox1" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Количество:</td>
                            <td>
                                <asp:TextBox ID="TextBox2" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Цена за голову:</td>
                            <td>
                                <asp:TextBox ID="TextBox3" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align: center">
                                <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Добавить" /></td>
                        </tr>
                    </table>
                    </div>
                    <div style="float: left; border: 1px black dashed;">
                        <table>
                            <tr>
                                <td>Общая стоимость поголовья:</td>
                                <td>
                                    <asp:TextBox ID="TextBox4" runat="server" Width="160px"></asp:TextBox></td>
                            </tr>
                            <tr>
                                <td colspan="2" style="text-align: center">
                                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Рассчитать" /></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>
