<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Cultures.aspx.cs" Inherits="Lab_4.Cultures1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Культуры</title>
    <style>
        .floatableDiv:after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    
        <div>
            <h1 style="font-family: Impact; background-color: greenyellow; text-align: center;">Просмотр сельскохозяйственных культур</h1>
            <span style="display: block; margin: 10px"><a href="/Main.aspx">Назад</a></span>
            <div>
                <asp:GridView HorizontalAlign="Center"  ID="CulturesTable" runat="server" DataKeyNames="IdC" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" OnSorting="CulturesTable_Sorting" OnRowCancelingEdit="CulturesTable_RowCancelingEdit" OnRowDeleting="CulturesTable_RowDeleting" OnRowEditing="CulturesTable_RowEditing" OnRowUpdating="CulturesTable_RowUpdating">
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <AlternatingRowStyle BackColor="White" />
                    <HeaderStyle BackColor="#28a4fb" Font-Bold="True" ForeColor="White" CssClass="Header" />
                    <Columns>
                        <asp:BoundField DataField="IdC" HeaderText="IdC" InsertVisible="False" ReadOnly="True" SortExpression="IdC" Visible="False" />
                        <asp:BoundField DataField="Cname" HeaderText="Наименование культуры" SortExpression="Cname" />
                        <asp:BoundField DataField="MarketPrice" HeaderText="Цена за тонну" SortExpression="MarketPrice" />
                        <asp:BoundField DataField="Count" HeaderText="Количество" SortExpression="Count" />
                    </Columns>
                </asp:GridView>
                
                <div class="floatableDiv" style="margin: 15px auto 10px; width: 800px">
                    <div style="float: left; margin-right: 15px; border: 1px black dashed;">
                        <table>
                        <tr>
                            <td>Наименование культуры:</td>
                            <td>
                                <asp:TextBox ID="TextBox1" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Количество:</td>
                            <td>
                                <asp:TextBox ID="TextBox2" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Цена за тонну:</td>
                            <td>
                                <asp:TextBox ID="TextBox3" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align: center">
                                <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Добавить" /></td>
                        </tr>
                    </table>
                    </div>
                    <div style="float: left; border: 1px black dashed;">
                        <table>
                            <tr>
                                <td>Ожидаемая выручка:</td>
                                <td>
                                    <asp:TextBox ID="TextBox4" runat="server" Width="160px"></asp:TextBox></td>
                            </tr>
                            <tr>
                                <td colspan="2" style="text-align: center">
                                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Рассчитать" /></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>

