<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Places.aspx.cs" Inherits="Lab_4.Places1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Рабочие отделы</title>
    <style>
        .floatableDiv:after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1 style="font-family: Impact; background-color: greenyellow; text-align: center;">Просмотр рабочих отделов</h1>
            <span style="display: block; margin: 10px"><a href="/Main.aspx">Назад</a></span>
            <div>
                <asp:GridView ID="PlacesTable" runat="server" HorizontalAlign="Center" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" DataKeyNames="IdP" OnRowDeleting="PlacesTable_RowDeleting" OnRowEditing="PlacesTable_RowEditing" OnRowCancelingEdit="PlacesTable_RowCancelingEdit" OnRowUpdating="PlacesTable_RowUpdating" OnSorting="PlacesTable_Sorting">
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <AlternatingRowStyle BackColor="White" />
                    <HeaderStyle BackColor="#28a4fb" Font-Bold="True" ForeColor="White" CssClass="Header" />
                    <Columns>
                        <asp:BoundField DataField="IdP" HeaderText="IdP" InsertVisible="False" ReadOnly="True" SortExpression="IdP" Visible="False" />
                        <asp:BoundField DataField="Pname" HeaderText="Название отдела" SortExpression="Pname" />
                        <asp:BoundField DataField="MPrice" HeaderText="Цена обслуживания за месяц" SortExpression="MPrice" />
                        <asp:TemplateField HeaderText="Возделываемая культура" SortExpression="PCulture">
                            <ItemTemplate><%# Eval("PCulture") %></ItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList
                                    ID="CultureEditor"
                                    DataSource='<%# GetCultureData() %>'
                                    DataTextField="Text"
                                    DataValueField="Id"
                                    SelectedValue='<%# Eval("PCultuteId") %>'
                                    runat="server" />
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Содержащиеся животные" SortExpression="PAnimals">
                            <ItemTemplate><%# Eval("PAnimals") %></ItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList
                                    ID="AnimalsEditor"
                                    DataSource='<%# GetAnimalsData() %>'
                                    DataTextField="Text"
                                    DataValueField="Id"
                                    SelectedValue='<%# Eval("PAnimalsId") %>'
                                    runat="server" />
                            </EditItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                
                <div class="floatableDiv" style="margin: 15px auto 10px; width: 900px">
                    <div style="float: left; margin-right: 15px; border: 1px black dashed;">
                        <table>
                        <tr>
                            <td>Название отдела:</td>
                            <td>
                                <asp:TextBox ID="TextBox1" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Цена облуживания за месяц:</td>
                            <td>
                                <asp:TextBox ID="TextBox2" runat="server" Width="160px"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Возделываемая культура:</td>
                            <td>
                                <asp:DropDownList ID="CultureDropDown" runat="server" /></td>
                        </tr>
                        <tr>
                            <td>Содержащиеся животные:</td>
                            <td>
                                <asp:DropDownList ID="AnimalsDropDown" runat="server" /></td>
                        </tr>
                       
                        <tr>
                            <td colspan="2" style="text-align: center">
                                <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Добавить" /></td>
                        </tr>
                    </table>
                    </div>
                    <div style="float: left; border: 1px black dashed;">
                        <table>
                            <tr>
                                <td>Обслуживание отделов за месяц:</td>
                                <td>
                                    <asp:TextBox ID="TextBox5" runat="server" Width="160px"></asp:TextBox></td>
                            </tr>
                            <tr>
                                <td colspan="2" style="text-align: center">
                                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click1" Text="Рассчитать" /></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>
