<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Workers.aspx.cs" Inherits="Lab_4.Workers1" %>
<%@ Import Namespace="System.Activities.Statements" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Просмотр работников</title>
</head>
<body>
    <form id="form1" runat="server">
        <p>
            Просмотр работников
        </p>
        <div>
            <a href="/Main.aspx">Вернуться на главную</a>
            <br />
            <br />
        </div>
        <asp:GridView ID="WorkersTable" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" DataKeyNames="IdW" OnRowDeleting="WorkersTable_RowDeleting" OnRowEditing="WorkersTable_RowEditing" OnRowCancelingEdit="WorkersTable_RowCancelingEdit" OnRowUpdating="WorkersTable_RowUpdating" OnSorting="WorkersTable_Sorting">
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <AlternatingRowStyle BackColor="White" />
            <HeaderStyle BackColor="#28a4fb" Font-Bold="True" ForeColor="White" CssClass="Header" />
            <Columns>
                <asp:BoundField DataField="IdW" HeaderText="IdW" InsertVisible="False" Visible="false" ReadOnly="True" SortExpression="IdW" />
                <asp:BoundField DataField="FName" HeaderText="Фамилия" SortExpression="FName" />
                <asp:BoundField DataField="SName" HeaderText="Имя" SortExpression="SName" />
                <asp:BoundField DataField="TName" HeaderText="Отчество" SortExpression="TName" />
                <asp:BoundField DataField="Wage" HeaderText="Зарплата" SortExpression="Wage" />
                <asp:TemplateField HeaderText="Инвентарь" SortExpression="Inv">
                    <ItemTemplate><%# Eval("Inv") %></ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList
                            ID="InvEditor"
                            DataSource='<%# GetInventoryData() %>'
                            DataTextField="Text"
                            DataValueField="Id"
                            SelectedValue='<%# Eval("InvId") %>'
                            runat="server"/>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Отдел" SortExpression="Place">
                    <ItemTemplate><%# Eval("Place") %></ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList
                            ID="PlaceEditor"
                            DataSource='<%# GetDepartmentData() %>'
                            DataTextField="Text"
                            DataValueField="Id"
                            SelectedValue='<%# Eval("PlaceId") %>'
                            runat="server"/>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="Login" HeaderText="Логин" SortExpression="Login" />
                <asp:BoundField DataField="Password" HeaderText="Пароль" SortExpression="Password" />
            </Columns>
        </asp:GridView>
        <div style="margin-top: 15px;">
            <div style="float: left; margin-right: 15px; border: 1px black dashed;">
                <table>
                    <tr>
                        <td>Фамилия:</td>
                        <td>
                            <asp:TextBox ID="TextBox6" runat="server" Width="160px"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td>Имя:</td>
                        <td>
                            <asp:TextBox ID="TextBox5" runat="server" Width="160px"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td>Отчество:</td>
                        <td>
                            <asp:TextBox ID="TextBox1" runat="server" Width="160px"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td>Зарплата:</td>
                        <td>
                            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td>Инвентарь:</td>
                        <td><asp:DropDownList ID="InventaryDropDown" runat="server"/></td>
                    </tr>
                    <tr>
                        <td>Отдел:</td>
                        <td><asp:DropDownList ID="DepartmentDropDown" runat="server" /></td>
                    </tr>
                    <tr>
                        <td>Логин:</td>
                        <td>
                            <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td>Пароль:</td>
                        <td>
                            <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center">
                            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Добавить" /></td>
                    </tr>
                </table>
            </div>
            <div style="float: left; border: 1px black dashed;">
                <table>
                    <tr>
                        <td>Общие затраты на зарплату:</td>
                        <td>
                            <asp:TextBox ID="TextBox9" runat="server" Width="160px"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center">
                            <asp:Button ID="Button3" runat="server" OnClick="Button2_Click" Text="Рассчитать" /></td>
                    </tr>
                </table>
            </div>
        </div>
    </form>
</body>
</html>
